<?php
declare(strict_types=1);

/**
 * End-to-end test for Phase 5 (company settings, formats, numbering, rules, labels, custom fields, print templates).
 *   php tests/settings.php http://127.0.0.1:8099        # against a throw-away database
 */
$base = rtrim($argv[1] ?? 'http://127.0.0.1:8099', '/');
require dirname(__DIR__) . '/core/bootstrap.php';
require __DIR__ . '/lib.php';

use Core\DB;

$sfx = bin2hex(random_bytes(3));
$sa = config('superadmin');
$admin = new Client($base);
$admin->post('/admin/login', ['email' => $sa['email'], 'password' => $sa['password']], '/admin/login');
$pro = (int)DB::val("SELECT id FROM plans WHERE slug = 'pro'");
$mk = function (string $name) use ($admin, $pro, $sfx, $base): array {
    $email = strtolower($name) . "-$sfx@test.local";
    $admin->post('/admin/tenants', ['name' => "$name $sfx", 'plan_id' => $pro, 'status' => 'active', 'subscription_ends_at' => '',
        'owner_name' => $name, 'owner_email' => $email, 'owner_password' => 'Password123'], '/admin/tenants/create');
    $c = new Client($base);
    $c->post('/login', ['email' => $email, 'password' => 'Password123'], '/login');
    return [$c, (int)DB::val('SELECT id FROM tenants WHERE name = ?', ["$name $sfx"])];
};
[$a, $tA] = $mk('Setco');
[$b, $tB] = $mk('Other');

$val = fn(string $sql, array $p = []) => DB::val($sql, $p);
$S = fn(string $k, int $t = null) => (string)DB::val('SELECT svalue FROM tenant_settings WHERE tenant_id = ? AND skey = ?', [$t ?? $GLOBALS['tA'], $k]);
$unit = fn(string $n) => (int)DB::val('SELECT id FROM units WHERE tenant_id = ? AND name = ?', [$GLOBALS['tA'], $n]);
$bal = fn(int $v) => (float)DB::val('SELECT COALESCE(SUM(qty),0) FROM stock_balances WHERE tenant_id = ? AND variant_id = ?', [$GLOBALS['tA'], $v]);
$ledger = fn() => (int)DB::val('SELECT COUNT(*) FROM stock_ledger WHERE tenant_id = ?', [$GLOBALS['tA']]);
$count = fn(string $t) => (int)DB::val("SELECT COUNT(*) FROM `$t` WHERE tenant_id = ?", [$GLOBALS['tA']]);
$main = (int)$val('SELECT id FROM warehouses WHERE tenant_id = ? AND is_default = 1', [$tA]);
$walk = (int)$val('SELECT id FROM customers WHERE tenant_id = ? AND is_walkin = 1', [$tA]);
$png = base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==');
$tmp = function (string $bytes, string $name, string $mime): CURLFile { $f = tempnam(sys_get_temp_dir(), 'up'); file_put_contents($f, $bytes); return new CURLFile($f, $mime, $name); };

echo "Settings pages\n";
check('/settings opens the company tab', str_ends_with((string)$a->get('/settings')['location'], '/settings/company'));
check('every settings tab loads', array_reduce(['company', 'preferences', 'numbering', 'workflow', 'labels', 'templates', 'formdesign', 'custom-fields/create'], fn($ok, $t) => $ok && $a->get("/settings/$t")['status'] === 200, true));
check('an unknown settings tab is a 404', $a->get('/settings/nonsense')['status'] === 404);

echo "Company profile and logo\n";
$post = fn(array $d, array $files = []) => $a->post('/settings/company', $d + $files, '/settings/company');
$post(['name' => "Setco Interiors $sfx", 'legal_name' => 'Setco Interiors Pvt Ltd', 'address' => "12 MG Road\nPune", 'phone' => '020-123', 'email' => 'hello@setco.test', 'website' => 'setco.test', 'tax_no' => '27ABCDE1234F1Z5', 'bank' => 'HDFC 0001 IFSC HDFC0000123']);
check('company name, legal name, address and tax number saved', $val('SELECT name FROM tenants WHERE id = ?', [$tA]) === "Setco Interiors $sfx" && $S('company.legal_name') === 'Setco Interiors Pvt Ltd' && $S('company.tax_no') === '27ABCDE1234F1Z5' && str_contains($S('company.address'), 'Pune'));
check('the new company name shows in the menu', str_contains($a->get('/dashboard')['body'], "Setco Interiors $sfx"));
$post(['name' => 'X', 'email' => 'not-an-email']);
check('an invalid company email is refused', $S('company.email') === 'hello@setco.test');
$post(['name' => '']);
check('an empty company name is refused', $val('SELECT name FROM tenants WHERE id = ?', [$tA]) === "Setco Interiors $sfx");
$post(['name' => "Setco Interiors $sfx", 'phone' => str_repeat('9', 100)]);
check('a too-long value is refused', $S('company.phone') === '020-123');
$post(['name' => "Setco Interiors $sfx", 'legal_name' => 'Setco Interiors Pvt Ltd', 'email' => 'hello@setco.test'], ['logo' => $tmp('this is not an image', 'logo.png', 'image/png')]);
check('a fake image is refused', $S('company.logo') === '');
$post(['name' => "Setco Interiors $sfx"], ['logo' => $tmp('<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>', 'logo.svg', 'image/svg+xml')]);
check('an SVG (can carry scripts) is refused', $S('company.logo') === '');
$post(['name' => "Setco Interiors $sfx"], ['logo' => $tmp($png . str_repeat("\0", 1100000), 'big.png', 'image/png')]);
check('a logo over 1 MB is refused', $S('company.logo') === '');
$post(['name' => "Setco Interiors $sfx", 'legal_name' => 'Setco Interiors Pvt Ltd', 'email' => 'hello@setco.test'], ['logo' => $tmp($png, 'logo.png', 'image/png')]);
$logo = $S('company.logo');
check('a real PNG is accepted and stored outside the web folder', preg_match('/^logo-' . $tA . '-[a-f0-9]+\.png$/', $logo) === 1 && is_file(ROOT . '/storage/uploads/' . $logo));
$lg = $a->get('/company/logo');
check('the logo is served with the right type', $lg['status'] === 200 && str_contains($lg['headers'], 'image/png') && str_contains($lg['headers'], 'nosniff') && $lg['body'] === $png);
check("another company cannot fetch it (404)", $b->get('/company/logo')['status'] === 404);
check('anonymous visitors cannot fetch it', str_ends_with((string)(new Client($base))->get('/company/logo')['location'], '/login'));
$post(['name' => "Setco Interiors $sfx", 'legal_name' => 'Setco Interiors Pvt Ltd', 'email' => 'hello@setco.test', 'remove_logo' => 1]);
clearstatcache();
check('the logo can be removed (file deleted)', $S('company.logo') === '' && !is_file(ROOT . '/storage/uploads/' . $logo));
$full = ['name' => "Setco Interiors $sfx", 'legal_name' => 'Setco Interiors Pvt Ltd', 'address' => "12 MG Road\nPune", 'phone' => '020-123', 'email' => 'hello@setco.test', 'website' => 'setco.test', 'tax_no' => '27ABCDE1234F1Z5', 'bank' => 'HDFC 0001 IFSC HDFC0000123'];
$post($full, ['logo' => $tmp($png, 'logo.png', 'image/png')]);
check('saving the whole profile again with a logo works', $S('company.logo') !== '' && $S('company.tax_no') === '27ABCDE1234F1Z5' && str_contains($S('company.bank'), 'HDFC 0001'));

echo "Currency and dates\n";
$a->post('/suppliers', ['name' => 'Big Supplier'], '/suppliers/create');
$sup = (int)$val("SELECT id FROM suppliers WHERE tenant_id = ? AND name = 'Big Supplier'", [$tA]);
$a->post('/items', ['name' => 'Velvet', 'unit_id' => $unit('Meter'), 'track_batch' => 1, 'variants' => [['sku' => 'VEL', 'cost_price' => 400, 'sale_price' => 700]]], '/items/create');
$a->post('/items', ['name' => 'Side Table', 'unit_id' => $unit('Piece'), 'variants' => [['sku' => 'TBL', 'barcode' => '111', 'cost_price' => 2500, 'sale_price' => 4200]]], '/items/create');
[$vel, $tbl] = array_map(fn($s) => (int)DB::val('SELECT id FROM item_variants WHERE tenant_id = ? AND sku = ?', [$tA, $s]), ['VEL', 'TBL']);
$a->post('/purchase/orders', ['supplier_id' => $sup, 'warehouse_id' => $main, 'order_date' => date('Y-m-d'), 'lines' => [['variant_id' => $tbl, 'qty' => 1000, 'unit_price' => 1234.5, 'tax_rate' => 0]]], '/purchase/orders/create');
$po = (int)$val('SELECT MAX(id) FROM purchase_orders WHERE tenant_id = ?', [$tA]);
$pg = $a->get("/purchase/orders/$po")['body'];
check('defaults: plain numbers with 2 decimals, ISO dates', str_contains($pg, '1,234,500.00') && str_contains($pg, date('Y-m-d')));
$pref = fn(array $d) => $a->post('/settings/preferences', $d, '/settings/preferences');
$pref(['symbol' => '₹', 'position' => 'before', 'decimals' => 2, 'grouping' => 'indian', 'date_format' => 'd-m-Y']);
$pg = $a->get("/purchase/orders/$po")['body'];
check('Indian grouping with a symbol: ₹ 12,34,500.00', str_contains($pg, '₹ 12,34,500.00'));
check('date in DD-MM-YYYY', str_contains($pg, date('d-m-Y')) && !str_contains($pg, '>' . date('Y-m-d') . '<'));
check('forms still use the ISO date for the date pickers', str_contains($a->get("/purchase/orders/$po/edit")['body'], 'value="' . date('Y-m-d') . '"'));
$pref(['symbol' => 'AED', 'position' => 'after', 'decimals' => 0, 'grouping' => 'intl', 'date_format' => 'd M Y']);
$pg = $a->get("/purchase/orders/$po")['body'];
check('symbol after, no decimals: 1,234,500 AED', str_contains($pg, '1,234,500 AED') && str_contains($pg, date('d M Y')));
$pref(['symbol' => 'TOOLONGSYMBOL', 'decimals' => 2, 'date_format' => 'Y-m-d']);
$pref(['symbol' => '$', 'decimals' => 9, 'date_format' => 'Y-m-d']);
$pref(['symbol' => '$', 'decimals' => 2, 'date_format' => 'zzz']);
check('a long symbol, 9 decimals and an unknown date format are refused', $S('currency.symbol') === 'AED' && $S('currency.decimals') === '0' && $S('date.format') === 'd M Y');
$pref(['symbol' => '', 'position' => 'before', 'decimals' => 2, 'grouping' => 'intl', 'date_format' => 'Y-m-d']);
check('formats can be set back', str_contains($a->get("/purchase/orders/$po")['body'], '1,234,500.00'));

echo "Document numbers\n";
$a->post('/purchase/orders', ['supplier_id' => $sup, 'warehouse_id' => $main, 'order_date' => date('Y-m-d'), 'lines' => [['variant_id' => $vel, 'qty' => 1, 'unit_price' => 1]]], '/purchase/orders/create');
check('default PO number is PO-0002', $val('SELECT po_no FROM purchase_orders WHERE tenant_id = ? ORDER BY id DESC LIMIT 1', [$tA]) === 'PO-0002');
$numbers = function (array $over = []) {
    $d = [];
    foreach (Core\Numbering::DOCS as $code => $_) $d[$code] = ['prefix' => $code, 'pad' => 4];
    foreach ($over as $code => $row) $d[$code] = $row;
    return ['num' => $d];
};
$post = fn(array $over) => $a->post('/settings/numbering', $numbers($over), '/settings/numbering');
$post(['PO' => ['prefix' => 'ord', 'pad' => 5, 'year' => 1], 'SO' => ['prefix' => 'SALE', 'pad' => 6]]);
check('numbering saved (prefix upper-cased)', str_contains($S('numbering.PO'), 'ORD') && str_contains($S('numbering.SO'), '"pad":6'));
$a->post('/purchase/orders', ['supplier_id' => $sup, 'warehouse_id' => $main, 'order_date' => date('Y-m-d'), 'lines' => [['variant_id' => $vel, 'qty' => 1, 'unit_price' => 1]]], '/purchase/orders/create');
$n1 = (string)$val('SELECT po_no FROM purchase_orders WHERE tenant_id = ? ORDER BY id DESC LIMIT 1', [$tA]);
$a->post('/purchase/orders', ['supplier_id' => $sup, 'warehouse_id' => $main, 'order_date' => date('Y-m-d'), 'lines' => [['variant_id' => $vel, 'qty' => 1, 'unit_price' => 1]]], '/purchase/orders/create');
$n2 = (string)$val('SELECT po_no FROM purchase_orders WHERE tenant_id = ? ORDER BY id DESC LIMIT 1', [$tA]);
check('new POs are ORD-<year>-00001, then 00002', $n1 === 'ORD-' . date('Y') . '-00001' && $n2 === 'ORD-' . date('Y') . '-00002');
check('old documents keep their numbers', (int)$val("SELECT COUNT(*) FROM purchase_orders WHERE tenant_id = ? AND po_no IN ('PO-0001', 'PO-0002')", [$tA]) === 2);
$a->post('/sales/orders', ['customer_id' => $walk, 'warehouse_id' => $main, 'order_date' => date('Y-m-d'), 'lines' => [['variant_id' => $tbl, 'qty' => 1, 'unit_price' => 1]]], '/sales/orders/create');
check('sales orders use SALE- with 6 digits', $val('SELECT order_no FROM sales_orders WHERE tenant_id = ? ORDER BY id DESC LIMIT 1', [$tA]) === 'SALE-000001');
check('the numbering page previews the next number', str_contains($a->get('/settings/numbering')['body'], 'ORD-' . date('Y') . '-00003') && str_contains($a->get('/settings/numbering')['body'], 'SALE-000002'));
$post(['PO' => ['prefix' => 'BAD PREFIX!', 'pad' => 4]]);
$post(['PO' => ['prefix' => 'WAYTOOLONGPREFIX', 'pad' => 4]]);
$post(['PO' => ['prefix' => 'PO', 'pad' => 2]]);
$post(['PO' => ['prefix' => 'PO', 'pad' => 12]]);
check('a bad prefix, a too-long prefix and 2 or 12 digits are refused', str_contains($S('numbering.PO'), 'ORD'));
$post([]);
$a->post('/purchase/orders', ['supplier_id' => $sup, 'warehouse_id' => $main, 'order_date' => date('Y-m-d'), 'lines' => [['variant_id' => $vel, 'qty' => 1, 'unit_price' => 1]]], '/purchase/orders/create');
check('numbers can be set back to the plain style (the counter continues)', preg_match('/^PO-\d{4}$/', (string)$val('SELECT po_no FROM purchase_orders WHERE tenant_id = ? ORDER BY id DESC LIMIT 1', [$tA])) === 1);
$a->post('/stock/adjustments', ['warehouse_id' => $main, 'reason' => 'opening', 'lines' => [['variant_id' => $tbl, 'qty' => 5]]], '/stock/adjustments/create');
check('stock documents and SKUs use the same numbering', (string)$val("SELECT doc_no FROM stock_docs WHERE tenant_id = ? AND type = 'adjustment' ORDER BY id DESC LIMIT 1", [$tA]) === 'ADJ-0001');
$b->post('/settings/numbering', ['num' => ['PO' => ['prefix' => 'ZZZ', 'pad' => 4]]], '/settings/numbering');
check("another company's numbering is its own", $S('numbering.PO', $tA) === '' || !str_contains($S('numbering.PO', $tA), 'ZZZ'));

echo "Rules: negative stock\n";
$wf = fn(array $d) => $a->post('/settings/workflow', $d, '/settings/workflow');
$wf([]);
$a->post('/stock/adjustments', ['warehouse_id' => $main, 'reason' => 'opening', 'lines' => [['variant_id' => $vel, 'qty' => 10, 'batch_id' => 'new', 'lot_no' => 'R1'], ['variant_id' => $vel, 'qty' => 10, 'batch_id' => 'new', 'lot_no' => 'R2']]], '/stock/adjustments/create');
$pos = fn(array $lines, array $over = []) => json_decode($a->post('/pos/checkout', $over + ['customer_id' => $walk, 'warehouse_id' => $main, 'method' => 'cash', 'amount' => 0, 'lines' => $lines], '/pos')['body'], true);
check('stock is 5 tables, 20 m of velvet', $bal($tbl) === 5.0 && $bal($vel) === 20.0);
$r = $pos([['variant_id' => $tbl, 'qty' => 8, 'unit_price' => 4200]]);
check('by default a sale beyond stock is refused', $r['ok'] === false && $bal($tbl) === 5.0);
$wf(['negative_stock' => 1]);
$r = $pos([['variant_id' => $tbl, 'qty' => 8, 'unit_price' => 4200]]);
check('with negative stock allowed the sale goes through and stock shows −3', $r['ok'] === true && $bal($tbl) === -3.0);
$r = $pos([['variant_id' => $vel, 'qty' => 25, 'unit_price' => 700]]);
check('fabric rolls can never go negative, even with the option on', $r['ok'] === false && $bal($vel) === 20.0);
$a->post('/stock/adjustments', ['warehouse_id' => $main, 'reason' => 'loss', 'lines' => [['variant_id' => $tbl, 'qty' => -4]]], '/stock/adjustments/create');
check('an adjustment can also take ordinary stock below zero', $bal($tbl) === -7.0);
$bad = DB::all('SELECT b.variant_id FROM stock_balances b LEFT JOIN (SELECT variant_id, warehouse_id, batch_id, location_id, SUM(qty_change) AS s FROM stock_ledger WHERE tenant_id = ? GROUP BY variant_id, warehouse_id, batch_id, location_id) l ON l.variant_id = b.variant_id AND l.warehouse_id = b.warehouse_id AND l.batch_id = b.batch_id AND l.location_id = b.location_id WHERE b.tenant_id = ? AND ABS(b.qty - COALESCE(l.s, 0)) > 0.0005', [$tA, $tA]);
check('the ledger still equals the balances', !$bad);
$wf([]);
$r = $pos([['variant_id' => $tbl, 'qty' => 1, 'unit_price' => 4200]]);
check('switching it off blocks selling from a negative balance again', $r['ok'] === false);
$a->post('/stock/adjustments', ['warehouse_id' => $main, 'reason' => 'found', 'lines' => [['variant_id' => $tbl, 'qty' => 20]]], '/stock/adjustments/create');

echo "Rules: shade (one roll per sale)\n";
$r = $pos([['variant_id' => $vel, 'qty' => 15, 'unit_price' => 700]]);
check('default "warn": 15 m from two 10 m rolls is allowed', $r['ok'] === true && $bal($vel) === 5.0);
$a->post('/stock/adjustments', ['warehouse_id' => $main, 'reason' => 'found', 'lines' => [['variant_id' => $vel, 'qty' => 15, 'batch_id' => 'new', 'lot_no' => 'R3']]], '/stock/adjustments/create');
$wf(['shade_rule' => 'block']);
$n = $ledger();
$r = $pos([['variant_id' => $vel, 'qty' => 18, 'unit_price' => 700]]);
check('"block": a sale that needs two rolls is refused', $r['ok'] === false && str_contains($r['error'], 'one roll') && $ledger() === $n);
$r = $pos([['variant_id' => $vel, 'qty' => 12, 'unit_price' => 700]]);
check('"block": a sale from a single roll still works', $r['ok'] === true);
$rolls = DB::all('SELECT b.id FROM batches b JOIN stock_balances s ON s.batch_id = b.id WHERE b.tenant_id = ? AND b.variant_id = ? AND s.qty > 0 ORDER BY b.id', [$tA, $vel]);
$a->post('/stock/adjustments', ['warehouse_id' => $main, 'reason' => 'found', 'lines' => [['variant_id' => $vel, 'qty' => 6, 'batch_id' => 'new', 'lot_no' => 'R4']]], '/stock/adjustments/create');
$rolls = DB::all('SELECT b.id FROM batches b JOIN stock_balances s ON s.batch_id = b.id WHERE b.tenant_id = ? AND b.variant_id = ? AND s.qty > 0 ORDER BY b.id', [$tA, $vel]);
$n = $ledger();
$a->post('/sales/deliveries', ['customer_id' => $walk, 'warehouse_id' => $main, 'delivery_date' => date('Y-m-d'), 'lines' => [
    ['variant_id' => $vel, 'qty' => 2, 'batch_id' => (int)$rolls[0]['id'], 'location_id' => 0, 'unit_price' => 700], ['variant_id' => $vel, 'qty' => 2, 'batch_id' => (int)$rolls[1]['id'], 'location_id' => 0, 'unit_price' => 700]]], '/sales/deliveries/create');
check('"block": picking two rolls by hand on a delivery is refused too', $ledger() === $n);
$wf([]);

echo "Rules: discount limit\n";
$staffRole = (int)DB::val("SELECT id FROM roles WHERE tenant_id = ? AND name = 'Staff'", [$tA]);
$a->post('/users', ['name' => 'Staff', 'email' => "staff-$sfx@test.local", 'password' => 'Password123', 'role_id' => $staffRole], '/users/create');
$s = new Client($base);
$s->post('/login', ['email' => "staff-$sfx@test.local", 'password' => 'Password123'], '/login');
$wf(['max_discount' => 10]);
check('the limit is saved', $S('max_discount') === '10');
$qt = fn(Client $c, float $disc) => $c->post('/sales/quotations', ['customer_id' => $walk, 'quote_date' => date('Y-m-d'), 'lines' => [['variant_id' => $tbl, 'qty' => 1, 'unit_price' => 4200, 'discount_pct' => $disc]]], '/sales/quotations/create');
$n = $count('sales_quotations');
$qt($s, 15);
check('staff cannot give 15% when the limit is 10%', $count('sales_quotations') === $n);
$qt($s, 8);
check('staff can give 8%', $count('sales_quotations') === $n + 1);
$qt($a, 15);
check('the owner is not limited', $count('sales_quotations') === $n + 2);
$res = json_decode($s->post('/pos/checkout', ['customer_id' => $walk, 'warehouse_id' => $main, 'method' => 'cash', 'amount' => 0, 'lines' => [['variant_id' => $tbl, 'qty' => 1, 'unit_price' => 4200, 'discount_pct' => 15]]], '/pos')['body'], true);
check('the counter enforces it as well', $res['ok'] === false && str_contains($res['error'], 'discount'));
$res = json_decode($s->post('/pos/checkout', ['customer_id' => $walk, 'warehouse_id' => $main, 'method' => 'cash', 'amount' => 0, 'lines' => [['variant_id' => $tbl, 'qty' => 1, 'unit_price' => 4200, 'discount_pct' => 10]]], '/pos')['body'], true);
check('exactly the limit is fine', $res['ok'] === true);
$wf(['max_discount' => 'abc']);
$wf(['max_discount' => 120]);
check('a bad limit is refused', $S('max_discount') === '10');
$wf([]);
check('"0" removes the limit', $S('max_discount') === '0');

echo "Rules: rack required, PO approval\n";
$a->post('/warehouses', ['name' => 'Showroom', 'code' => 'SHW'], '/warehouses/create');
$show = (int)$val("SELECT id FROM warehouses WHERE tenant_id = ? AND name = 'Showroom'", [$tA]);
DB::insert('locations', ['tenant_id' => $tA, 'warehouse_id' => $main, 'code' => 'A-01']);
$A1 = (int)$val("SELECT id FROM locations WHERE tenant_id = ? AND code = 'A-01'", [$tA]);
$wf(['require_rack' => 1]);
$n = $ledger();
$a->post('/stock/adjustments', ['warehouse_id' => $main, 'reason' => 'found', 'lines' => [['variant_id' => $tbl, 'qty' => 1, 'location_id' => 0]]], '/stock/adjustments/create');
check('stock into a warehouse with racks needs a rack', $ledger() === $n);
$a->post('/stock/adjustments', ['warehouse_id' => $main, 'reason' => 'found', 'lines' => [['variant_id' => $tbl, 'qty' => 1, 'location_id' => $A1]]], '/stock/adjustments/create');
check('...and works with one', $ledger() === $n + 1);
$a->post('/stock/adjustments', ['warehouse_id' => $show, 'reason' => 'found', 'lines' => [['variant_id' => $tbl, 'qty' => 1, 'location_id' => 0]]], '/stock/adjustments/create');
check('a warehouse without racks is not affected', $ledger() === $n + 2);
$a->post('/stock/adjustments', ['warehouse_id' => $main, 'reason' => 'loss', 'lines' => [['variant_id' => $tbl, 'qty' => -1, 'location_id' => $A1]]], '/stock/adjustments/create');
check('taking stock out never needs a rack choice', $ledger() === $n + 3);
$g = $count('grns');
$a->post('/purchase/grns', ['supplier_id' => $sup, 'warehouse_id' => $main, 'received_date' => date('Y-m-d'), 'lines' => [['variant_id' => $tbl, 'qty' => 2, 'unit_price' => 1, 'location_id' => 0]]], '/purchase/grns/create');
check('a goods receipt without a rack is refused', $count('grns') === $g);
$a->post('/purchase/grns', ['supplier_id' => $sup, 'warehouse_id' => $main, 'received_date' => date('Y-m-d'), 'lines' => [['variant_id' => $tbl, 'qty' => 2, 'unit_price' => 1, 'location_id' => $A1]]], '/purchase/grns/create');
check('...and accepted with one', $count('grns') === $g + 1);
$wf([]);
$wf(['po_approval' => 1]);
$a->post('/purchase/orders', ['supplier_id' => $sup, 'warehouse_id' => $main, 'order_date' => date('Y-m-d'), 'lines' => [['variant_id' => $tbl, 'qty' => 1, 'unit_price' => 1]]], '/purchase/orders/create');
$poA = (int)$val('SELECT MAX(id) FROM purchase_orders WHERE tenant_id = ?', [$tA]);
$a->post("/purchase/orders/$poA/submit", [], "/purchase/orders/$poA");
check('PO approval switched on from Settings makes a PO wait for approval', $val('SELECT status FROM purchase_orders WHERE id = ?', [$poA]) === 'pending_approval');
$wf([]);

echo "Labels\n";
$lab = fn(array $l) => $a->post('/settings/labels', ['label' => $l], '/settings/labels');
$a->post('/suppliers', ['name' => 'Supplier Nation Ltd'], '/suppliers/create');
$lab(['supplier' => ['Vendor', 'Vendors'], 'rack' => ['Bin', ''], 'customer' => ['Client', 'Clients'], 'batch' => ['Roll', 'Rolls']]);
$dash = $a->get('/dashboard')['body'];
check('the menu uses the new words', str_contains($dash, '>Vendors<') && str_contains($dash, 'Clients') && str_contains($dash, 'Bins / locations') && str_contains($dash, '>Rolls<') && !str_contains($dash, '>Suppliers<'));
$sp = $a->get('/suppliers')['body'];
check('titles, headings and buttons follow', str_contains($sp, 'Add vendor') && str_contains($sp, '<title>Vendors'));
check('the plural is guessed when you only give one word (Bin → Bins)', str_contains($a->get('/stock/racks')['body'], 'Bins') || str_contains($dash, 'Bins'));
check("your data is never rewritten: a supplier called 'Supplier Nation Ltd' keeps its name", str_contains($sp, 'Supplier Nation Ltd'));
check('form field names and links are untouched (filters still work)', str_contains($a->get('/purchase/orders')['body'], 'name="supplier"') && $a->get("/purchase/orders?supplier=$sup")['status'] === 200);
$lab(['supplier' => ['<script>', '']]);
check('names with symbols are refused', str_contains($S('labels'), 'Vendor'));
$lab(['supplier' => ['', ''], 'rack' => ['', ''], 'customer' => ['', ''], 'batch' => ['', '']]);
check('empty boxes bring the standard words back', $S('labels') === '[]' && str_contains($a->get('/dashboard')['body'], '>Suppliers<'));
$b->post('/settings/labels', ['label' => ['supplier' => ['Vendor', 'Vendors']]], '/settings/labels');
check("another company's labels do not leak", str_contains($a->get('/dashboard')['body'], '>Suppliers<'));

echo "Custom fields\n";
$cf = fn(array $d) => $a->post('/settings/custom-fields', $d, '/settings/custom-fields/create');
$cf(['entity' => 'item', 'type' => 'number', 'label' => 'Fabric width (inch)', 'is_required' => 1, 'show_in_list' => 1, 'sort_order' => 1]);
$cf(['entity' => 'item', 'type' => 'dropdown', 'label' => 'Finish', 'options' => "Matt\nGloss\nSatin", 'sort_order' => 2]);
$cf(['entity' => 'customer', 'type' => 'date', 'label' => 'Birthday']);
$cf(['entity' => 'customer', 'type' => 'checkbox', 'label' => 'Preferred dealer', 'show_in_list' => 1]);
$cf(['entity' => 'supplier', 'type' => 'text', 'label' => 'Preferred courier', 'show_in_list' => 1]);
$field = fn(string $e, string $l) => (int)DB::val('SELECT id FROM custom_fields WHERE tenant_id = ? AND entity = ? AND label = ?', [$GLOBALS['tA'], $e, $l]);
[$fWidth, $fFinish, $fBday, $fDealer, $fCourier] = [$field('item', 'Fabric width (inch)'), $field('item', 'Finish'), $field('customer', 'Birthday'), $field('customer', 'Preferred dealer'), $field('supplier', 'Preferred courier')];
check('five fields created', $fWidth && $fFinish && $fBday && $fDealer && $fCourier);
$cf(['entity' => 'item', 'type' => 'text', 'label' => 'Finish']);
check('a duplicate field name is refused', (int)$val("SELECT COUNT(*) FROM custom_fields WHERE tenant_id = ? AND entity = 'item' AND label = 'Finish'", [$tA]) === 1);
$cf(['entity' => 'item', 'type' => 'dropdown', 'label' => 'Bad dropdown', 'options' => 'Only one']);
$cf(['entity' => 'item', 'type' => 'checkbox', 'label' => 'Bad checkbox', 'is_required' => 1]);
$cf(['entity' => 'nonsense', 'type' => 'text', 'label' => 'Nope']);
$cf(['entity' => 'item', 'type' => 'text', 'label' => '']);
check('a one-choice dropdown, a required checkbox, an unknown place and an empty name are refused', !$field('item', 'Bad dropdown') && !$field('item', 'Bad checkbox') && !$field('item', 'Nope') && $count('custom_fields') === 5);
check('fields appear on the new item form', str_contains($a->get('/items/create')['body'], 'Fabric width (inch)') && str_contains($a->get('/items/create')['body'], 'Satin'));
$itemPost = fn(array $cfv, string $name = 'Cotton') => $a->post('/items', ['name' => $name, 'unit_id' => $unit('Meter'), 'variants' => [['sku' => 'COT-' . bin2hex(random_bytes(2))]], 'cf' => $cfv], '/items/create');
$n = $count('items');
$itemPost([]);
check('a required custom field must be filled', $count('items') === $n);
$itemPost([$fWidth => 'wide']);
check('a number field refuses text', $count('items') === $n);
$itemPost([$fWidth => '54', $fFinish => 'Sparkly']);
check('a dropdown refuses a value that is not in its list', $count('items') === $n);
$itemPost([$fWidth => '54', $fFinish => 'Matt']);
$cot = (int)$val("SELECT id FROM items WHERE tenant_id = ? AND name = 'Cotton'", [$tA]);
check('a valid item saves its custom values', $cot > 0 && $val('SELECT value FROM custom_field_values WHERE field_id = ? AND entity_id = ?', [$fWidth, $cot]) === '54' && $val('SELECT value FROM custom_field_values WHERE field_id = ? AND entity_id = ?', [$fFinish, $cot]) === 'Matt');
$page = $a->get("/items/$cot")['body'];
check('the item page shows them', str_contains($page, 'Fabric width (inch)') && str_contains($page, '54') && str_contains($page, 'Matt'));
check('the item list shows the "show in list" column', str_contains($a->get('/items')['body'], '<th>Fabric width (inch)</th>'));
$a->post("/items/$cot", ['name' => 'Cotton', 'unit_id' => $unit('Meter'), 'is_active' => 1, 'variants' => [['id' => (int)$val('SELECT id FROM item_variants WHERE item_id = ?', [$cot]), 'sku' => (string)$val('SELECT sku FROM item_variants WHERE item_id = ?', [$cot])]], 'cf' => [$fWidth => '60', $fFinish => '']], "/items/$cot/edit");
check('editing changes and clears values', $val('SELECT value FROM custom_field_values WHERE field_id = ? AND entity_id = ?', [$fWidth, $cot]) === '60' && !$val('SELECT 1 FROM custom_field_values WHERE field_id = ? AND entity_id = ?', [$fFinish, $cot]));
check('the edit form is pre-filled with the saved value', str_contains($a->get("/items/$cot/edit")['body'], 'value="60"'));
$custPost = fn(array $cfv, string $name) => $a->post('/customers', ['name' => $name, 'cf' => $cfv], '/customers/create');
$custPost([$fBday => '1990-02-30'], 'Bad Date');
check('an impossible date is refused', !$val("SELECT 1 FROM customers WHERE tenant_id = ? AND name = 'Bad Date'", [$tA]));
$custPost([$fBday => '1990-05-17', $fDealer => '1'], 'Dealer Dan');
$dan = (int)$val("SELECT id FROM customers WHERE tenant_id = ? AND name = 'Dealer Dan'", [$tA]);
check('date and yes/no values saved on a customer', $dan > 0 && $val('SELECT value FROM custom_field_values WHERE field_id = ? AND entity_id = ?', [$fBday, $dan]) === '1990-05-17' && $val('SELECT value FROM custom_field_values WHERE field_id = ? AND entity_id = ?', [$fDealer, $dan]) === '1');
$cp = $a->get("/customers/$dan")['body'];
check('the customer page shows "Yes" and the date', str_contains($cp, 'Preferred dealer') && str_contains($cp, 'Yes') && str_contains($cp, '1990-05-17'));
check('the customer list shows the yes/no column', str_contains($a->get('/customers')['body'], '<th>Preferred dealer</th>'));
$a->post('/suppliers', ['name' => 'Courier Co', 'cf' => [$fCourier => 'BlueDart']], '/suppliers/create');
$cc = (int)$val("SELECT id FROM suppliers WHERE tenant_id = ? AND name = 'Courier Co'", [$tA]);
check('supplier custom text saved, shown on the page and in the list', $val('SELECT value FROM custom_field_values WHERE field_id = ? AND entity_id = ?', [$fCourier, $cc]) === 'BlueDart' && str_contains($a->get("/suppliers/$cc")['body'], 'BlueDart') && str_contains($a->get('/suppliers')['body'], 'BlueDart'));
$a->post("/settings/custom-fields/$fFinish", ['label' => 'Surface', 'type' => 'number', 'options' => "Matt\nGloss", 'sort_order' => 5, 'is_active' => 1], "/settings/custom-fields/$fFinish/edit");
check('a field can be renamed but its type is fixed', $val('SELECT label FROM custom_fields WHERE id = ?', [$fFinish]) === 'Surface' && $val('SELECT type FROM custom_fields WHERE id = ?', [$fFinish]) === 'dropdown');
$a->post("/settings/custom-fields/$fWidth", ['label' => 'Fabric width (inch)', 'sort_order' => 1], "/settings/custom-fields/$fWidth/edit");
check('an inactive field disappears from the form and is no longer required', !str_contains($a->get('/items/create')['body'], 'Fabric width (inch)') && (function () use ($itemPost, $count) { $n = $count('items'); $itemPost([], 'No Width Needed'); return $count('items') === $n + 1; })());
check('...but its saved values are kept', $val('SELECT value FROM custom_field_values WHERE field_id = ? AND entity_id = ?', [$fWidth, $cot]) === '60');
$a->post("/settings/custom-fields/$fWidth/delete", [], '/settings/custom-fields/create');
check('deleting a field deletes its values', !$val('SELECT 1 FROM custom_fields WHERE id = ?', [$fWidth]) && !$val('SELECT 1 FROM custom_field_values WHERE field_id = ?', [$fWidth]));
check("another company sees none of A's fields and cannot edit them", !str_contains($b->get('/items/create')['body'], 'Surface') && $b->get("/settings/custom-fields/$fBday/edit")['status'] === 404);
$b->post("/settings/custom-fields/$fBday/delete", [], '/settings/custom-fields/create');
check("another company cannot delete A's field", (bool)$val('SELECT 1 FROM custom_fields WHERE id = ?', [$fBday]));
$bUnit = (int)$val("SELECT id FROM units WHERE tenant_id = ? AND name = 'Piece'", [$tB]);
$b->post('/items', ['name' => 'B Item', 'unit_id' => $bUnit, 'variants' => [['sku' => 'BI']], 'cf' => [$fBday => 'hijack', $fCourier => 'hijack']], '/items/create');
check("values posted for another company's field ids are ignored", !$val('SELECT 1 FROM custom_field_values WHERE tenant_id = ?', [$tB]));

echo "Print templates\n";
$tpl = fn(string $doc, array $d) => $a->post('/settings/templates', $d + ['doc' => $doc], "/settings/templates?doc=$doc");
$a->post('/sales/deliveries', ['customer_id' => $dan, 'warehouse_id' => $main, 'delivery_date' => date('Y-m-d'), 'make_invoice' => 1, 'lines' => [['variant_id' => $vel, 'qty' => 2, 'batch_id' => (int)$rolls[0]['id'], 'location_id' => 0, 'unit_price' => 700, 'discount_pct' => 5, 'tax_rate' => 12]]], '/sales/deliveries/create');
$inv = (int)$val('SELECT MAX(id) FROM sales_invoices WHERE tenant_id = ?', [$tA]);
$dlv = (int)$val('SELECT MAX(id) FROM deliveries WHERE tenant_id = ?', [$tA]);
$qid = (int)$val('SELECT MAX(id) FROM sales_quotations WHERE tenant_id = ?', [$tA]);
check('templates tab offers a preview link once a document exists', str_contains($a->get('/settings/templates?doc=invoice')['body'], "sales/invoices/$inv/print"));
$pr = $a->get("/sales/invoices/$inv/print")['body'];
check('default invoice shows the logo, legal name, address, tax number, discount column, bank details and roll', str_contains($pr, 'company/logo') && str_contains($pr, 'Setco Interiors Pvt Ltd') && str_contains($pr, '12 MG Road') && str_contains($pr, '27ABCDE1234F1Z5') && str_contains($pr, '>Disc<') && str_contains($pr, 'HDFC 0001') && str_contains($pr, 'Roll '));
$tpl('invoice', ['title' => 'My Invoice', 'show_logo' => '', 'show_company' => 1, 'accent' => '#ff0000', 'show_tax' => 1, 'show_batch' => '', 'terms' => 'Pay within 7 days', 'footer' => 'See you soon', 'signature' => 1, 'signature_label' => 'Boss']);
$pr = $a->get("/sales/invoices/$inv/print")['body'];
check('the edited invoice: new heading, no logo, no discount column, no roll, terms, footer, signature text, accent colour, no bank block', str_contains($pr, 'My Invoice') && !str_contains($pr, 'company/logo') && !str_contains($pr, '>Disc<') && !str_contains($pr, 'Roll ') && str_contains($pr, 'Pay within 7 days') && str_contains($pr, 'See you soon') && str_contains($pr, 'Boss') && str_contains($pr, '#ff0000') && !str_contains($pr, 'HDFC 0001'));
$tpl('invoice', ['title' => 'X', 'accent' => 'red']);
check('a bad accent colour is refused', str_contains($S('template.invoice'), '#ff0000'));
$tpl('invoice', ['title' => 'X', 'accent' => '#112233', 'terms' => str_repeat('a', 2000)]);
check('over-long terms are refused', str_contains($S('template.invoice'), '#ff0000'));
$tpl('nonsense', ['title' => 'X']);
check('an unknown template is a 404', $a->post('/settings/templates', ['doc' => 'nonsense'], '/settings/templates')['status'] === 404);
$tpl('receipt', ['title' => 'Cash memo', 'footer' => 'Come again', 'signature' => '', 'show_company' => 1, 'accent' => '#000000']);
$rc = $a->get("/sales/invoices/$inv/print?receipt=1")['body'];
check('the counter receipt has its own template', str_contains($rc, 'Cash memo') && str_contains($rc, 'Come again') && !str_contains($rc, 'My Invoice'));
$dn = $a->get("/sales/deliveries/$dlv/print");
check('delivery note: roll numbers shown, prices hidden by default, "Received by"', $dn['status'] === 200 && str_contains($dn['body'], 'Delivery note') && str_contains($dn['body'], 'Received by') && !str_contains($dn['body'], 'Amount') && str_contains($dn['body'], 'Roll'));
$tpl('delivery_note', ['title' => 'Challan', 'show_prices' => 1, 'show_batch' => 1, 'show_rack' => 1, 'show_ship_to' => 1, 'show_company' => 1, 'accent' => '#000000', 'signature' => 1, 'signature_label' => 'Customer sign']);
$dn = $a->get("/sales/deliveries/$dlv/print")['body'];
check('delivery note can show prices and the rack, with its own words', str_contains($dn, 'Challan') && str_contains($dn, 'Amount') && str_contains($dn, '>Rack<') && str_contains($dn, 'Customer sign'));
$tpl('purchase_order', ['title' => 'Order to supplier', 'show_tax' => 1, 'show_expected' => 1, 'show_bank' => 1, 'show_company' => 1, 'accent' => '#00aa00', 'terms' => 'Deliver in 10 days', 'signature' => 1, 'signature_label' => 'Purchaser']);
$pp = $a->get("/purchase/orders/$po/print");
check('purchase order print: its template, supplier block, terms and bank details', $pp['status'] === 200 && str_contains($pp['body'], 'Order to supplier') && str_contains($pp['body'], 'Big Supplier') && str_contains($pp['body'], 'Deliver in 10 days') && str_contains($pp['body'], 'HDFC 0001') && str_contains($pp['body'], 'Purchaser'));
$qp = $a->get("/sales/quotations/$qid/print");
check('quotation print uses its default terms', $qp['status'] === 200 && str_contains($qp['body'], 'Quotation') && str_contains($qp['body'], 'valid until the date shown'));
check('print buttons are on the document pages', str_contains($a->get("/sales/deliveries/$dlv")['body'], "deliveries/$dlv/print") && str_contains($a->get("/purchase/orders/$po")['body'], "orders/$po/print") && str_contains($a->get("/sales/quotations/$qid")['body'], "quotations/$qid/print"));
check("another company cannot print A's documents (404)", $b->get("/sales/invoices/$inv/print")['status'] === 404 && $b->get("/sales/deliveries/$dlv/print")['status'] === 404 && $b->get("/purchase/orders/$po/print")['status'] === 404 && $b->get("/sales/quotations/$qid/print")['status'] === 404);
check("another company's template is independent", $S('template.invoice', $tB) === '' && !str_contains($b->get('/settings/templates?doc=invoice')['body'], 'My Invoice'));

echo "Permissions\n";
check('staff can read the settings pages', $s->get('/settings/company')['status'] === 200 && $s->get('/settings/formdesign')['status'] === 200 && $s->get('/settings/templates')['status'] === 200 && $s->get('/company/logo')['status'] === 200);
$before = $S('company.phone');
$s->post('/settings/company', ['name' => 'Hacked', 'phone' => '000'], '/settings/company');
$s->post('/settings/workflow', ['negative_stock' => 1], '/settings/workflow');
$s->post('/settings/numbering', ['num' => ['PO' => ['prefix' => 'HACK', 'pad' => 4]]], '/settings/numbering');
check('staff cannot change company details, rules or numbers (403)', $S('company.phone') === $before && $val('SELECT name FROM tenants WHERE id = ?', [$tA]) === "Setco Interiors $sfx" && $S('negative_stock') === '0' && !str_contains($S('numbering.PO'), 'HACK'));
check('staff cannot add custom fields or open the field form (403)', $s->get('/settings/custom-fields/create')['status'] === 403 && $s->get("/settings/custom-fields/$fBday/edit")['status'] === 403);
check('staff see items with custom fields but get a clean form', $s->get("/items/$cot")['status'] === 200);

echo $fails ? "\n$fails check(s) FAILED\n" : "\nAll checks passed\n";
exit($fails ? 1 : 0);
