<div class="card" style="max-width:560px"><div class="card-body">
<form method="post" action="<?= url("purchase/bills/{$b['id']}") ?>"><?= csrf_field() ?>
<?php if (ff('bill.supplier_bill_no')): ?>  <div class="mb-3"><label class="form-label"><?= e(term('supplier')) ?>'s bill number<?= ffstar('bill.supplier_bill_no') ?></label><input name="supplier_bill_no"<?= ffreq('bill.supplier_bill_no') ?> class="form-control" maxlength="60" value="<?= e(old('supplier_bill_no', $b['supplier_bill_no'] ?? '')) ?>"></div><?php else: ?><?= ffh('bill.supplier_bill_no', e(old('supplier_bill_no', $b['supplier_bill_no'] ?? ''))) ?><?php endif; ?>
  <div class="row"><div class="col-md-6 mb-3"><label class="form-label">Bill date</label><input type="date" name="bill_date" class="form-control" value="<?= e(old('bill_date', $b['bill_date'])) ?>" required></div>
    <?php if (ff('bill.due_date')): ?><div class="col-md-6 mb-3"><label class="form-label">Due date<?= ffstar('bill.due_date') ?></label><input type="date" name="due_date"<?= ffreq('bill.due_date') ?> class="form-control" value="<?= e(old('due_date', $b['due_date'] ?? '')) ?>"></div><?php else: ?><?= ffh('bill.due_date', old('due_date', $b['due_date'] ?? '')) ?><?php endif; ?></div>
  <?php if (ff('bill.other_charges')): ?><div class="mb-3"><label class="form-label">Other charges on the bill (freight, packing…)<?= ffstar('bill.other_charges') ?></label><input type="number" step="0.01" min="0" name="other_charges"<?= ffreq('bill.other_charges') ?> class="form-control" value="<?= e(old('other_charges', $b['other_charges'])) ?>">
    <div class="form-text">Goods <?= e(money($b['subtotal'])) ?> + tax <?= e(money($b['tax_total'])) ?> + these charges = bill total.</div></div><?php else: ?><?= ffh('bill.other_charges', old('other_charges', $b['other_charges'])) ?><?php endif; ?>
<?php if (ff('bill.notes')): ?>  <div class="mb-3"><label class="form-label">Notes<?= ffstar('bill.notes') ?></label><input name="notes"<?= ffreq('bill.notes') ?> class="form-control" maxlength="255" value="<?= e(old('notes', $b['notes'] ?? '')) ?>"></div><?php else: ?><?= ffh('bill.notes', e(old('notes', $b['notes'] ?? ''))) ?><?php endif; ?>
  <button class="btn btn-primary">Save</button> <a class="btn btn-link" href="<?= url("purchase/bills/{$b['id']}") ?>">Cancel</a>
</form></div></div>
