<form method="post" action="<?= url('purchase/grns') ?>"><?= csrf_field() ?>
<?php if ($po): ?><input type="hidden" name="po_id" value="<?= (int)$po['id'] ?>"><span id="hasPo" hidden></span><?php endif; ?>
<div class="card mb-3"><div class="card-body"><div class="row g-3 <?= ffclass('grn') ?>"><?= ffextras('grn', [], []) ?>
  <div class="col-md-4"><label class="form-label"><?= e(term('supplier')) ?></label>
    <?php if ($po): ?><input class="form-control" value="<?= e($po['supplier']) ?>" disabled>
    <?php else: ?><select name="supplier_id" class="form-select" required><option value="">Choose…</option>
      <?php foreach ($suppliers as $s): ?><option value="<?= (int)$s['id'] ?>" <?= (int)old('supplier_id') === (int)$s['id'] ? 'selected' : '' ?>><?= e($s['name']) ?></option><?php endforeach; ?></select><?php endif; ?></div>
  <div class="col-md-3"<?= ffa('grn.warehouse_id') ?>><label class="form-label"><?= fl('grn.warehouse_id', 'Receive into') ?></label><select name="warehouse_id" id="warehouse_id" class="form-select" required>
    <?php foreach ($warehouses as $w): ?><option value="<?= (int)$w['id'] ?>" <?= (int)old('warehouse_id', $po['warehouse_id'] ?? 0) === (int)$w['id'] ? 'selected' : '' ?>><?= e($w['name']) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-2"<?= ffa('grn.received_date') ?>><label class="form-label"><?= fl('grn.received_date', 'Received on') ?></label><input type="date" name="received_date" class="form-control" value="<?= e(old('received_date', date('Y-m-d'))) ?>" required></div>
<?php if (ff('grn.supplier_ref')): ?>  <div class="col-md-3"<?= ffa('grn.supplier_ref') ?>><label class="form-label"><?= fl('grn.supplier_ref', e(term('supplier')) . ' challan / invoice no.') ?><?= ffstar('grn.supplier_ref') ?></label><input name="supplier_ref"<?= ffreq('grn.supplier_ref') ?> class="form-control" maxlength="60" value="<?= e(old('supplier_ref')) ?>"></div><?php else: ?><?= ffh('grn.supplier_ref', e(old('supplier_ref'))) ?><?php endif; ?>
<?php if (ff('grn.extra_cost')): ?>  <div class="col-md-3"<?= ffa('grn.extra_cost') ?>><label class="form-label"><?= fl('grn.extra_cost', 'Extra cost (freight, duty…)') ?><?= ffstar('grn.extra_cost') ?></label><input type="number" step="0.01" min="0" name="extra_cost"<?= ffreq('grn.extra_cost') ?> class="form-control" value="<?= e(old('extra_cost')) ?>"></div><?php else: ?><?= ffh('grn.extra_cost', e(old('extra_cost'))) ?><?php endif; ?>
<?php if (ff('grn.extra_cost_note')): ?>  <div class="col-md-4"<?= ffa('grn.extra_cost_note') ?>><label class="form-label"><?= fl('grn.extra_cost_note', 'Extra cost note') ?><?= ffstar('grn.extra_cost_note') ?></label><input name="extra_cost_note"<?= ffreq('grn.extra_cost_note') ?> class="form-control" maxlength="150" value="<?= e(old('extra_cost_note')) ?>"></div><?php else: ?><?= ffh('grn.extra_cost_note', e(old('extra_cost_note'))) ?><?php endif; ?>
<?php if (ff('grn.note')): ?>  <div class="col-md-5"<?= ffa('grn.note') ?>><label class="form-label"><?= fl('grn.note', 'Note') ?><?= ffstar('grn.note') ?></label><input name="note"<?= ffreq('grn.note') ?> class="form-control" maxlength="255" value="<?= e(old('note')) ?>"></div><?php else: ?><?= ffh('grn.note', e(old('note'))) ?><?php endif; ?>
</div>
<p class="text-muted small mt-3 mb-0">Fabric / <?= e(term('batch', true)) ?>-tracked <?= e(term('items', true)) ?>: <strong>each line is one roll (thaan)</strong> and becomes its own <?= e(term('batch', true)) ?> on the <?= e(term('rack', true)) ?> you choose. If a delivery has 3 rolls of the same fabric, use <em>＋ split</em> to add a line per roll.
  Extra cost is spread over the <?= e(term('items', true)) ?> by value and becomes part of their stock cost; it does not change the <?= e(term('supplier', true)) ?>'s bill.</p></div></div>
<?php $mode = 'grn'; $noAdd = (bool)$po; require __DIR__ . '/_lines.php'; ?>
<button class="btn btn-success">Receive into stock</button> <a class="btn btn-link" href="<?= $po ? url("purchase/orders/{$po['id']}") : url('purchase/grns') ?>">Cancel</a>
</form>
